server:
  port: 8060
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9098/realms/real-estate-microservice/protocol/openid-connect/certs

application:
  config:
    properties-url: http://localhost:9090/api/v1/properties

api:
  admin-acc-prefix: api/v1/admin/accounts
  acc-prefix: api/v1/accounts

jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60