eureka:
  client:
    register-with-eureka: false

server:
  port: 9090

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: properties
          uri: http://properties-service:8050/
          predicates:
            - Path=/api/v1/properties/**

        - id: account
          uri: http://account-service:8060/
          predicates:
            - Path=/api/v1/accounts/**, /api/v1/admin/accounts/**

        - id: property-submissions
          uri: http://property-submissions-service:8070/
          predicates:
            - Path=/api/v1/property-submissions/**

        - id: payment
          uri: http://payment-service:8080/
          predicates:
            - Path=/api/v1/payment/**

        - id: listing-services
          uri: http://listing-service-service:8090/
          predicates:
            - Path=/api/v1/listing-services/**

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: "http://keycloak:8080/realms/real-estate-microservice"
#          jwk-set-uri: "http://keycloak:8080/realms/real-estate-microservice/protocol/openid-connect/certs"

app:
  eureka-server: discovery-server

api:
  prefix: api/v1/accounts

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true