server:
  port: 9011

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: properties
          uri: http://property-service:8050/
          predicates:
            - Path=/api/v1/properties/**

        - id: account
          uri: http://account-service:8060/
          predicates:
            - Path=/api/v1/accounts/**, /api/v1/admin/accounts/**

        - id: property-submissions
          uri: http://property-submissions-service:8070/
          predicates:
            - Path=/api/v1/property-submissions/**

        - id: payment
          uri: http://payment-service:8080/
          predicates:
            - Path=/api/v1/payment/**

        - id: listing-services
          uri: http://listing-service-service:8090/
          predicates:
            - Path=/api/v1/listing-services/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak:8080/realms/real-estate-microservice"
          jwk-set-uri: "http://keycloak:8080/realms/real-estate-microservice/protocol/openid-connect/certs"

app:
  eureka-server: discovery-server

api:
  prefix: api/v1/accounts

# Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      tracing:
        endpoint: "http://zipkin:9411/api/v2/spans"

# Actuator Endpoint
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

# Eureka
eureka:
  client:
    register-with-eureka: false