eureka:
  client:
    register-with-eureka: false
server:
  port: 9090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: login
          uri: http://localhost:8080/
          predicates:
            - Path=/api/v1/login
        - id: properties
          uri: http://localhost:8050/
          predicates:
            - Path=/api/v1/properties/**
        - id: account
          uri: http://localhost:8060/
          predicates:
            - Path=/api/v1/account/**, /api/v1/admin/accounts/**
        - id: property-submissions
          uri: http://localhost:8070/
          predicates:
            - Path=/api/v1/property-submissions/**
        - id: payment
          uri: http://localhost:8080/
          predicates:
            - Path=/api/v1/payment/**