spring:
  application:
    name: properties-service
  config:
    import: optional:configserver:http://localhost:8888
#  profiles:
#    active: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9098/realms/real-estate-microservice/protocol/openid-connect/certs
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
