spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
            authorization-uri: ${KEYCLOAK_AUTH_SERVER_URL}
            token-uri: ${KEYCLOAK_TOKEN_URI}
            user-info-uri: ${KEYCLOAK_USER_INFO_URI}
            jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${KEYCLOAK_REDIRECT_URI}
            scope:
              - openid
              - profile
              - email
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}

#logging:
#  level:
#    root: debug
#    org.springframework.security: debug
#    org.springframework.security.oauth2: DEBUG
#    org.springframework.security.authentication: DEBUG
