spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/real-estate-microservice"
          jwk-set-uri: "http://localhost:8080/realms/real-estate-microservice/protocol/openid-connect/certs"
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
