eureka:
  client:
    register-with-eureka: false
server:
  port: 9090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: login
          uri: http://localhost:8080/
          predicates:
            - Path=/api/v1/login
        - id: properties
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/properties/**
        - id: property-category
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/property-category/**
        - id: account
          uri: http://localhost:8083/
          predicates:
            - Path=/api/v1/account/**

management:
  tracing:
    sampling:
      probability: 1.0