spring:
  application:
    name: payment-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:9098/realms/real-estate-microservice/protocol/openid-connect/certs"